export const GET_ACCOUNTS = 'GET_ACCOUNTS';
export const LOAD_ACCOUNTS='LOAD_ACCOUNTS'
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const GET_TRANSACTIONS='GET_TRANSACTIONS'